### ISSUE TITLE
Richard - Enough Houses?

### ISSUE THREAD

**Issue by XJDL** [Evrey/SHC_AIV#1]
Does Richard build enough houses? In my games, he is not able to build any troops after he build up his castle, because there are no recruits.

**Comment by Evrey** [comment]
The houses *should* be enough, as they match the number of houses Firefly gave them. Salah also has this issue. Guess I have to add some.

**Comment by Evrey** [comment]
Fixed it. I ensured that Richard now has at least 9 houses and Saladin builds up to 14.
