### ISSUE TITLE
Asking help for a small problem

### ISSUE THREAD

**Issue by gloeyisk** [Evrey/SHC_AIV#22]
I know this is wrong place to ask, but I need help.
I've a plan to play Crusader Extreme map in regular Crusader. Had basic knowledge to use the Crusader MapTools but unfortunately the map isn't playable even not detected inside the game, I've change the map to Unlock as well. Thank you.

**Comment by Evrey** [comment]
This is indeed not the right place. I don't play this game anymore and I have no idea what the problem may be. Sorry, but I guess you'll have to ask someone else.
