### ISSUE TITLE
AI can easily be rushed

### ISSUE THREAD

**Issue by NoTitleGamesOfficial** [Evrey/SHC_AIV#25]
While every ai's castle might be better, they seem to need a bit longer to build their first troops. 
I can rush every ai with 20 mounted archers

**Comment by Evrey** [comment]
Hey, thanks for the interest.

However, in that case the mod is just not for you. I don’t like rushing, it’s a sign of broken gameplay. So this is a »won’t fix«.

This repository is archived anyway, i left the Stronghold community years ago.
