### ISSUE TITLE
Lionheart Easteregg

### ISSUE THREAD

**Issue by JoshuaTeakles** [Evrey/SHC_AIV#3]
Hey Evrey, in your Description your talking about how the Lionheart castle is an Easteregg in itself. However, the castle from the title screen uses the smallest possible tower instead of the medium one (as you can see here: http://vignette2.wikia.nocookie.net/steamtradingcards/images/c/c8/Stronghold_Crusader_HD_Artwork_2.jpg/revision/latest?cb=20140913003458)

Just a small thing, besides this, I am loving the new castles and the eastereggs - especially the smiley face ;)

**Comment by Evrey** [comment]
This is known. The reason for that is that Tower 2 is already in use for Richard's outer wall. To quote the `README.md`:

> Well, *the two smaller towers are different*, but all in all Richard now builds the castle from the cover art and title screen of Stronghold Crusader.

Thanks for the Issue anyways!

**Comment by Evrey** [comment]
By the way, this has been "fixed" in Richard's even newer castles. =)
