### ISSUE TITLE
Frederick lacks trebuchet line of sight

### ISSUE THREAD

**Issue by Heroesflorian** [Evrey/SHC_AIV#5]
For your Frederick castles, you placed trebuchets within the castle, surrounded by walls. 
Even when it is "only" a low wall, it still blocks the line of sight for any trebuchets closely behind it, causing them to promptly stop hurling out any further rocks. 

This makes Frederick's defensive trebuchets essentially useless for the rest of the game, as soon as his outer walls are built, unless a) that wall later gets destroyed, allowing (temporarily) line of sight for trebuchets until the wall gets repaired, or b) the trebuchets sometimes by chance manage to find line of sight to some hostile target under some weird angle, e.g. shooting sideways, parallel to the walls in front of them. 
Both of those cases aren't particularly likely/frequent, though, but rather "edge cases" or "exceptions" in a way... so mostly, the trebuchets will be inactive for most of the time in any game. 

I suggest placing them outside the walls instead, with a clear line of sight at least in the forward direction. You can possibly protect them with killing pits, moats or possibly dog cages, but not with wall or any tall buildings (blocking line of sight). 

And yes, this AI behaviour is a bit unfortunate and different from what a human player would/could do, but it is like this for all AI characters as far as I know. You can also observe this in action e.g. on the vanilla wolf5.aiv where the Wolf has several trebuchet spots inside his castle... those trebuchets will never be able to shoot unless that castle's front tower gets destroyed, in which case the trebuchets start firing as soon as the tower goes down, and cease fire as soon as it gets rebuilt.

**Comment by Evrey** [comment]
Weird? My observation so far was that trebuchets will attack anything in range, no matter the line of sight, under the condition that the bombarded castle belongs to an enemy who is the current target of the next siege.

Guess I should have a second look at it.

By the way, this also applies to the Wolf.

**Comment by Heroesflorian** [comment]
Trebuchets indeed only bombard the castle (and economic buildings) of the enemy who is their current attack target. Especially noticeable for AI characters who switch targets solely based on enemy gold stocks, those will not let their trebuchets attack their neighbour when another opponent far away has more gold... but that only makes it more important to make sure trebuchets can fire as often as possible by not blocking line of sights. 

And yes, it also applies to the Wolf... I forgot to include him in the post as right when I was writing it, I thought of Udwin's Mission 50 video where Wolf's trebuchets were mostly able to fire at Udwin - as a quick check revealed, that was thanks to holes in the exterior wall (caused by nearby water), though, which maintained trebuchets' line of sight to Udwin's castle. 

One more thing: I think sometimes it could even be beneficial to **partially** block trebuchet line of sight, to prevent them from shooting sideways at hostile farms or woodcutters, and instead concentrate more on castle defenses in front of the trebuchet. 
This is due to trebuchets often just picking the nearest hostile building and not the most appropriate one to shoot at with a trebuchet, and wasting 5 or 10 rocks to destroy a single woodcutter hut or apple orchard is not quite efficient... 
What amount of LoS-blocking would be desirable may differ depending on the situation, though.

**Comment by Evrey** [comment]
Oh this is fuckin' amazing...

Don't get me wrong - I love your bug reports, you do awesome work here! It just annoys me every time how... *"weird"* a certain game's engine is at times.

Well then, Frederick will be an easy fix. The Wolf on the other hand will require a complete re-work of the outer walls and moats of all his castles. I am so much looking forward to doing it.

I cannot say when I'll be in the mood for modding again, perhaps in a week, perhaps later, so if you feel capable enough and willing to fix things earlier, I'll welcome your pull request with open arms. =)

**Comment by Heroesflorian** [comment]
Hahaha, a certain game's engine, or AI behavior, is very weird indeed... also causes me problems with my own AIVs every now and then, as well as general facepalm moments (e.g. "Störkatapulte" just getting built over with tents for new ones, and the AI just generally halting their creation after a while, AI often not getting back resources for deleted buildings when they were seen as inaccessible, handling of engineers guild / oil smelter / tunnelors guild squares not getting removed along their buildings, etc.). 
Recently I even encountered a bug in the AIV editor that will most likely cause me to have to redo large parts of a rather complex AIV because the current version of the AIV is stuck without the ability to remove any pauses whatsoever, nor add any new ones beyond step 249... and 249 is the limit exactly because 250 (249+1) is the max "_pause delay_" that can be set in the AIV editor, which ofc should have nothing to do with the pause's _location_, normally... arghhh... guess you don't happen to know a fix for that issue by chance? :D

Anyway... I haven't really looked at all of your Frederick/Wolf castles in detail yet, I merely just watched Udwin's skirmish trail let's play where some of them can be seen in action and noticed some things here and there basically, and then took a quick look at 2-3 of the Frederick AIVs to confirm what I had seen, so I'm not quite sure I want to "mess with your creations" on my own, especially when a "complete re-work of the outer walls and moats of all his castles" is required. 
But I'll have to see, maybe if I get some spare time I'll have a go at it.

**Comment by Evrey** [comment]
> the current version of the AIV is stuck without the ability to remove any pauses whatsoever,[...]
>
> [...] guess you don't happen to know a fix for that issue by chance? :D

A little piece of wisdom from modder to modder: Fuck pauses. With good ordering of the most important initial stuff, pauses do nothing but make the AI lords vulnerable to rushes.

> But I'll have to see, maybe if I get some spare time I'll have a go at it.

Whoever of us might be first. =D

As for the Wolf's outer walls: I'd basically rebuild those sections where the walls leave space for trebuchets, so that they tightly enclose the higher walls behind. The trebuchets might then be enclosed with death pits. For Frederick, I'd just fill the space where the trebuchets were with gardens or something.

**Comment by Heroesflorian** [comment]
> A little piece of wisdom from modder to modder: Fuck pauses. With good ordering of the most important initial stuff, pauses do nothing but make the AI lords vulnerable to rushes.

Oh well, with the AI's priorities, pauses can help getting the "the keep is enclosed" achievement earlier. AI generally tend to continue building additional rows of walls and crenellations otherwise, instead of building towers and gatehouses... I feel pauses help a little bit there. 
Also, my first pause on that AIV is at step 150, with a not too long delay, and at that point the castle is enclosed and the most important buildings and exterior economy are all well-built already. 
The pause also helps to ~~make sure~~ increase the chances of Saladin manning some of his more important buildings first before placing more unoccupied stuff when he has enough starting goods to go "troop spamming mode". 

Either way, as stated, the bug also prevents removing (or moving) existing pauses so... meh...

**Comment by Evrey** [comment]
Moved Friedrich's trebuchets. Mind giving your blessings? And please open a second issue for the Wolf's trebs.

**Comment by Heroesflorian** [comment]
One aspect that is now a bit more pronounced than before, due to putting the trebs further to the front (further forward than the walls, obviously) is that they are all very front-facing. Which is fine with me... but this means they may see a lot of "traffic", and thus for the killing pits around the trebuchets (and yes, I checked, some castles had those already before, but before I just didn't put my attention to them) I would say the placement could be slightly optimized. 

![grafik](https://user-images.githubusercontent.com/12549394/33828051-c7f5b56e-de6a-11e7-8838-dcddf312bb2b.png)

E.g. here, 2 of the 3 trebuchets might get reached and destroyed by hostile (melee) troops with a simple frontal assault without stepping into a single killing pit. In contrast, some of the killing pits in between the trebuchets will most likely never get "activated" by hostile troops, at least not by troops going for the trebuchets, and by troops going for the castle itself not before the trebuchets already were destroyed. 

Now, clearly this is "Meckern auf hohem Niveau", and I wouldn't say it's a big issue, but yeah. 

One more thing I try to keep in mind is that the AI tries to build trebuchet 1 first, then 2, then 3, so I usually make sure to place the 1. spot in that location that is safest/closest to the engineers guild and castle gates, as the AI is dumb enough to send their engineers out right into enemy fire as well, and then it is better to have one safe trebuchet up and running before trying to set up the one in the most dangerous position. 
In your case, you mostly have 3 trebuchets right next to each other in a row parallel to the castle, so I would guess it doesn't really matter here. 

Overall, trebs are now in front of the walls and look like they'd have enough empty space to be built properly, so should be fine. 👍 

>  And please open a second issue for the Wolf's trebs.

I will.

**Comment by Evrey** [comment]
The non-optimised positioning of traps is pretty much "on purpose", just as for outer houses. They are meant to be "good enough". The ordering of trebs is a good point, but as long as the current solution works fine, I'd call it good enough.

So, I'll close this issue for now and thank you for your report!
