### ISSUE TITLE
Wolf lacks trebuchet line of sight

### ISSUE THREAD

**Issue by Heroesflorian** [Evrey/SHC_AIV#7]
In a very similar way to Frederick* previously, Wolf also features some defensive trebuchets behind own castle walls that block their line of sight and thus prevent them from shooting. 

Clearly, that's no desired behavior, trebuchets should have free LoS towards the enemy. 

(* for reference, see https://github.com/Evrey/SHC_AIV/issues/5 )

**Comment by Evrey** [comment]
And as mentioned in #5 , I'm open for pull requests fixing that issue, as I cannot say when I'll be motivated enough to do that myself. Modding SHC is pretty frustrating at times. What I'd expect from pull requests:

- The 3 trebs are put in front of the Wolf's outer wall.
- The trebs should be put at the center of a 5x5 square area with nothing else in there. Otherwise, bugs might prevent trebs from being built, although they only need a 3x3 area.
- The trebs should be protected by one rectangular line of killing pits connecting to the outer castle wall.
- Killing pits must not connect to diagonal walls. That just looks ugly.
- The former outer wall and moat have to be re-built to fit tightly around the castle's front. I.e. no empty space should be left where the old trebs were.
- Ensure that the placed trebs are ID 1, 2, and 3, as the AI will *never* build ID 4 and 5.
- Keep the original build order. I.e., if the old outer front crenel was built at step 50, then the fixes should start at step 50 as well. If traps in front of gates are not built before step 150, then the traps around trebs should be built somewhere after step 150 as well.

Huh... writing that down makes it sound more complicated than it is. Anyways, this issue is a TODO.

**Comment by Heroesflorian** [comment]
What about those cases where there are alternating trebuchets and gardens or houses? Should those buildings then be re-located (e.g. to the back or sides of the castle) as well, or left in their original location? In the situation of the pic below (wolf1.aiv), for example, leaving them in place would certainly work, but not really allow much of a change to the walls, even when putting the buildings a bit closer together. 

Also, for wolf4.aiv, some of the fire ballistae already are closer to the wall than would be ideal. Putting the trebs outside the wall as well would work, but probably then all siege engines would be squished together pretty much, so maybe it would be better to place the trebuchets to the sides of the castle instead (near the front ofc)? 

![grafik](https://user-images.githubusercontent.com/12549394/33837945-421eee6e-de8e-11e7-8318-8f39352e4f9f.png)

**Comment by Heroesflorian** [comment]
_gentle bump_
Would be good if you can quickly clarify the above points. Maybe I will give it a try then in the near future.

**Comment by Evrey** [comment]
Huh, didn't get notified about that december post. Or I accidentally marked it as read. Anyways...

> What about those cases where there are alternating trebuchets and gardens or houses?

Just throw 'em somewhere else, I guess.

> Also, for wolf4.aiv [...]

I'm not entirely sure what would be the best solution here. Just try something, I guess?

**Comment by Heroesflorian** [comment]
I just started work on the wolf AIVs. 
For wolf4.aiv, the problematic one, I am not quite sure what to go for, yet. Two options I am particularly taking into consideration are: 

![image](https://user-images.githubusercontent.com/12549394/36125363-fb09fe2c-1053-11e8-9a59-8bff6b048df9.png)

1. (left) Put the trebuchets at the front-left / front-right corner areas next to the castle, at (or close to) their current "forward-coordinate". Has the advantage that there is plenty of space to finetune the positioning and place killing pits around the trebuchet. Also makes it easy to treat the castle's "entrance tunnel pitch trap" completely separately from the trebuchets when trying to find a good new shape for the walls, e.g. creating a small indent that houses a fire ballista and provides a bit of interior space for e.g. a statue. 
Has the disadvantage that the central "clustering" of siege engines from the original design is lost, and also makes the trebuchets considerably more vulnerable when hostile melee or ranged units attack from the sides, as the trebuchets will be the "point of first contact" there. Walking distance for engineers trying to set up and man the trebuchets is also longer, and with the trebuchets being "point of first contact, the engineers' chances to get shot is higher. Last but not least, only two trebuchets (one left, one right) would fit in with this variant. The central fire ballista in front of the gate tunnel also requires one row of killing pits to be removed. 

2. (right) Put the trebuchets in the central area together with the fire ballistae. Has the advantage that this design can fit a full three trebuchets and three fire ballistae, and does not have any of those right in front of the gate / entrance. Not having a ballista in the entrance-way can be visually more pleasing, more safe for the ballista, and frees up that space to use for something else (e.g. more killing pits and/or pitch ditch, a dog cage or something decorative like a may pole, garden or possibly even stocks - those are kind of humane compared to other punishments, after all). Also, the central cluster of siege engines is very protected to the sides by the castle's fortifications, unlike variant 1. 
Has the disadvantage that there is less space for killing pits around the trebuchets. Also, as one cannot equally distribute 3 fire ballistae and 3 trebuchets on two equal halves, this design is slightly asymmetric by default: While symmetric in terms of "where do any siege engines stand", one side would have 2 trebuchets and 1 fire ballista, the other one 2 fire ballistae and 1 trebuchet - or 3 / 3, to accentuate the asymmetry, might look interesting as well... Last but not least, preserving the "entrance tunnel pitch trap" and coming up with a feasible wall layout is a bit harder. 
--
The picture above shows one possible variant for preserving the "entrance tunnel pitch trap", using moat to recreate the original entrance tunnel. Alternatively, a small alley of statues could be used to the same effect, or a more forward-extending wall similar to the example of variant 1. visible on the left. Or, one could just fill that currently-moated area with more pitch and/or killing pits. With no fancy indents and no completely unchanged preservation of the original entrance tunnel, but plenty of alternative variants to make up for that, this design can be just as much of an opportunity as it is a challenge, of course. 

Note: For both variants, in the above picture I removed pitch ditches where intersecting with the siege engine locations. If one is willing to sacrifice own siege engines to set enemies on fire when being attacked (can be feasible), both designs could be "completed" by adding (back) some pitch ditches near/on the siege engine locations.

**Comment by Evrey** [comment]
I really like the left solution to the problem, pick that one. It has a much more organic way of preserving the pitch path of doom. You may cut the low wall one tile short so that it better aligns with the killing pits of the pitch path of doom.

**Comment by Heroesflorian** [comment]
![image](https://user-images.githubusercontent.com/12549394/36284044-97075df2-12a6-11e8-8852-b3ffefc9e6f4.png)
😃 

WIP, obviously, but I like that building step.

**Comment by Evrey** [comment]
> WIP, obviously, but I like that building step.

You fudgy bastard. =D

> Also, I just noticed one can place troop spots on the very outline of the AIV editor's build area.

Huh, the more you know.

> [...] should I do that [move trebs to the front line] or stick to the previous iteration with trebs to the sides of the castle [...]?

I'd say move trebs 1 and 2 to the sides, treb 3 in front of the killing pits. Move Fbal 1 and 2 into the carved-out sections and Fbal 3 to the back gate.

In addition to that: What do you think of this?

![wf4-mock](https://user-images.githubusercontent.com/6483505/36304576-6ad46882-1310-11e8-8666-eeed3d5a6e2e.png)

*(Note, I do not have a dedicated WINE setup for SHC and modding right now, so I just made a quick mockup.)*

This way, the path along the moat has a better looking thickness and the siege engines look less squeezed. I also sacrificed path of doom length in favour of a second full pitch moat in front of the siege engines. Doesn't leave much space for putting something behind the outer wall, but I'd call that a non-issue.

**Comment by Heroesflorian** [comment]
Ugh... You know you _could_ have come up with that _before_ I fiddled around long enough to get the crenellations for those nice indents you seemed to like a lot into one building step? 🙈 

Anyway, sure if you now want to split the "path of doom" up into one shorter part and one broad line further forward, we could do that. 

> This way, the path along the moat has a better looking thickness and the siege engines look less squeezed. (...) Doesn't leave much space for putting something behind the outer wall, but I'd call that a non-issue.

Sure, space inside of that wall is a non-issue. So is, I'd say, the thickness of the path along the moat, though. As long as it is walkable, I wouldn't worry too much about it, as it lies between walls anyway, so ingame you will see little to nothing of it. Hence, I would rather optimize for aesthetic exterior wall shapes over aesthethic unseen path shapes.

**Comment by Evrey** [comment]
> Ugh... You know you could have come up with that before I fiddled around long enough to get the crenellations for those nice indents you seemed to like a lot into one building step?

Well, yeah, I could... errm... anyways! =D

> As long as [the moat path] is walkable, I wouldn't worry too much about it, as it lies between walls anyway, so ingame you will see little to nothing of it. Hence, I would rather optimize for aesthetic exterior wall shapes over aesthethic unseen path shapes.

Well, that's a good point you make. So the two carves it is. The empty space between moat and wall can then be filled with two statues.

**Comment by Heroesflorian** [comment]
Just getting back to that one... here a quick ingame SS of the current version for Wolf4 with the compact siege engine cluster: 

![image](https://user-images.githubusercontent.com/12549394/36936605-c6aa3594-1f07-11e8-93f5-491a90aa8469.png)

The current state of planning was... uh, moving trebs out to the sides and possibly changing the indents or leaving them as they are?

**Comment by Heroesflorian** [comment]
I think we can close this issue for now, as all relevant aspects of it have been covered in the #10 branch by now, with only (potentially) some final "cosmetic details" remaining but all functionality complete. 
For the merging details, #10 is the better place for further discussion when necessary.
