### ISSUE TITLE
Nazir's pitch ditches

### ISSUE THREAD

**Issue by Heroesflorian** [Evrey/SHC_AIV#8]
Your Nizars have some far-out pitch ditches, and then a huge amount of "nothing" between those and the castle itself. 
I understand filling it all with pitch ditches would be a bit OTT, quite expensive and possibly (due to farms and such) unreliable, but only having some small ditches far off is at least affected by the unreliability argument as well, possibly even more so. The further from the keep you go, the less certain can you typically be about what is there on different maps. 

So I wonder, why not add some more (small) pitch ditches here and there (not everywhere ofc)? 
Even just a very few tiles of pitch here and there can be enough to scare human players after encountering the slightly larger outer pitches and losing half of their troops there on their first approach... and at the same time, a very few tiles of pitch here and there should be still affordable and not too OP against other AI characters or most humans either. 

There may be valid reasons for deciding against it, such as vanilla Nizar having no pitches at all and you not wanting to pitch-up the Nizar too much, or keeping average time duration till the castle is finished and Nizar can focus on troops solely as short as possible, but I'd love to hear your thoughts on this topic.

**Comment by Evrey** [comment]
The idea with them was to surprise players with a seemingly large death radius. You further approach the castle and seemingly nothing's there, until you reach oil pot range. His walls are also directly protected by a moat, so there's not that much pressure to burn everyone immediately.

I might add a second pitch ring in front of the moat, but yeah, filling the blanks is definitely overkill.

**Comment by Heroesflorian** [comment]
Yeah, a second ring at the moat or somewhere in between might be neat. 
Anyway, which is the reason I write the comment, I just wanted to mention really like the basic idea of a surprisingly large death radius. 
Just had a really good mean laugh on one of Udwin's videos, e.g. here: 
https://youtu.be/OviSOSeqLYg?t=1094

**Comment by Evrey** [comment]
Ah yes, the Gesäßgebäck. =D

I might add a second ring in the near future. ;)

**Comment by Evrey** [comment]
I decided not to extend the ditches any further. I kinda like them the way they are. Instead, gimme my `Sbw`s for the Wolf back, game! D:<
