### ISSUE TITLE
Nizar lacks a brain when starting with low goods

### ISSUE THREAD

**Issue by Heroesflorian** [Evrey/SHC_AIV#9]
So there I just put your Nizar against a Richard Lionheart on a balanced 1 vs 1 testing map with all necessary resources available, and 2k starting gold for both. Now, I was excited to see who would win (Richard's catapult/trebuchet spam vs helpless Nizar, or Nizar's assassins vs Richard's helpless always-closed gate), but to my surprising, the game was decided already after 3 game years, and ended after exactly 12 game years, with Nizar being defeated. I noticed the reason, but still tried again and restarted the game, and watched as the events repeated exactly the same way as in the first game. Below is the end statistics of the first game. 

![grafik](https://user-images.githubusercontent.com/12549394/35838020-7b60da34-0ae9-11e8-9ba0-f15f56e273b0.png)

Alone by looking at the statistics, it becomes obvious that Nizar didn't quite get up and running at the start, producing 0 food throughout the entirety of the game. 

So enough blabbering, what was happening there? Nizar spent all of his starting wood and gold on building wheat farms, bakeries, breweries, mercenary post, engineers guild, houses, trading post, granary, and even woodcutter huts and an iron mine - but he didn't build a mill, essentially stalling all of his bread production. 
A couple years into the game, his start food was gone and his popularity started dropping as he was out of gold, still had no mill, and had not gotten to build hops farms and inns either, and positive fear factor alone wasn't enough to keep up his popularity. 5 years into the game, Nizar then was down to 4 workers (3 wheat farmers, 1 woodcutter) and still had no mill. 

![grafik](https://user-images.githubusercontent.com/12549394/35838518-fad2390a-0aeb-11e8-8507-3153bbf99dce.png)

Shortly after, in total 6 years into the game, Richard's first attack smashed Nizar's front wall and some of his buildings, and with Nizar still down at 0 popularity, 4 workers, 0 mills it didn't take too long afterwards until Richard hat flattened all of Nizar's buildings in and around his castle, and killed his Lord with some pitch-ditch-induced delay. 

All in all, this greatly reminded me of vanilla Wazir's poor performance with low starting goods, as can be seen in detail on that AI battle video: https://youtu.be/Tu4BQgsD_kE Wazir had the same issue there, didn't place his mill, ran out of food, popularity drop, game over. 

His initial starting wood was spent on other buildings (e.g. farms, houses, trading post, possibly even an iron mine) before it was the first mill's turn on the AIV's build order, and when the mill finally would have been built, Wazir (or now, Nizar) is out of wood already and the mill will be skipped for the time being. 
Later, even with a bit of gold left to trade, or woodcutters bringing in more wood, the AI will usually reach lower thresholds first, e.g. 10 wood for a bakery, and build that first, being back to square one... and of course, initial soldier recruiting will make short work of any remaining start gold reserves or early income from a single iron mine or selling a bit of surplus wheat. 
When food runs out before all those 10-wood buildings and other stuff has been built, popularity will drop, and the AI has no gold left to buy food (or, for Wazir, doesn't buy food in general) or set negative taxes to try and counter this... 
This behaviour can be less obvious when starting with many goods and gold, as more start wood increases chances for a successful mill placement, and lots of gold gives the AI more time/chances to buy wood (and/or food) and eventually hopefully get going with their mill, or at least get going enough other industry to then have a steady income large enough to fund food and wood for a mill later. Also, ironically, on maps that lack resources so that the AI just cannot build particularly much external industry right away, this issue is less present. 

At this point in time you might be full of rage about my wall of text, and about the incompetence of Crusader's AI behaviour, yet I would argue this should certainly be fixable by slightly modifying the castle's build order. 
Key here is setting the first mill very early in the build order, so that it has good chances to be built before that iron mine and other less relevant external industry, plus leaving a number of steps AFTER the mill during which no bakeries or other wooden buildings get placed in the AIV, but rather walls, a first tower, a moat or whatever else, to "buy some time" for the mill to be built even when the starting wood wasn't sufficient for building it right away and the AI checks through the next steps if anything else can be built with less than 20 wood. 
It may sound trivial, but it seems to be quite promising. 

And in case you think this is crazily stupid/buggy AI behaviour, I am currently facing bizarre problems with one of my own AIVs that make this issue here seem like the most straight-forward thing ever... but I guess that's a story for another time, unless you want a deluxe facepalm moment 🙈

**Comment by Evrey** [comment]
Yupp, I know about this pathetic bug. It affects **every** AI lord making bread. Your solution for the problem is really neat. I think I'd make the first mill of every bread baker the very first building in the queue, even before the stock pile extension, as wood always comes first. Perhaps no re-ordering of other buildings will be needed this way.

Lookin' at my current gaming and hobby schedule, it is very unlikely that I'll fix this within the next months. Not impossible, but very unlikely. So, if you are faster, then you're welcome to help, otherwise be patient. =D

Nice bug report as always, btw.!

**Comment by Heroesflorian** [comment]
Yeah I know you're working hard to make AEI great :) Yet I am not sure I can find the time to deal with the issue in a timely manner either... having the idea of changing the build order is one thing, adjusting it on all 8 castles and then testing if it works and if necessary finetuning the build order to make sure it works fine is another thing... anyway maybe I can fit it in somewhen... 
Well, I suppose it may not take that much longer than writing long bug reports after all xD With an ingame speed of 125 multiplied by a factor of "theoretical 16", AI battles run quite fast compared to regular 90 x 1 speed. 

And I see you finally saw the December post for Wolf that I made and then forgot about it... :D Good.

**Comment by Evrey** [comment]
[This commit](https://github.com/Evrey/SHC_AIV/commit/0861c910da920754472919a924b2a6068883536e) should fix it. I did what I threatened to do: I made the windmills the very first building in the queue, even before the stockpile addons.
